DUT = pio_core

VERILOG_SOURCES = \
	$(CURDIR)/../../../src/pc_register.v \
	$(CURDIR)/../../../src/register.v \
	$(CURDIR)/../../../src/delay_counter.v \
	$(CURDIR)/../../../src/pio_core.v

include ../common.mk